String Banana_t = "Banana Benefits";
String Banana_d =
    "Nutrition facts\n\nThe nutrition facts for 1 medium-sized banana\n(100 grams) are (1Trusted Source):\nCalories: 89\nWater: 75%\nProtein: 1.1 grams\nCarbs: 22.8 grams\nSugar: 12.2 grams\nFiber: 2.6 grams\nFat: 0.3 grams\nCarbs\nBananas are a rich source of carbs, which\noccur mainly as starch in unripe bananas and\nsugars in ripe bananas.\nBananas boast a number of health benefits.\nHeart health\nHeart disease is the world’s most common\ncause of premature death.\nBananas are high in potassium, a mineral that\npromotes heart health and normal blood\npressure. One medium-sized banana contains\naround 0.4 grams of this mineral.\nAccording to a large analysis of many\nstudies, daily consumption of 1.3–1.4 grams\nof potassium is linked to a 26% lower risk of\nheart disease (10Trusted Source).\nIn addition, bananas contain antioxidant\nflavonoids also associated with a significant\ndecrease in heart disease risk (11Trusted\nSource).";
// String Apple
// String Black_grapes
// String Black_raspberries
String Grapes_t = "grape Benefits";
String Grapes_d =
    "Grape Nutrition Facts One cup of grapes (92g) provides 62 calories, 0.6g of protein, 16g of carbohydrates, and 0.3g of fat. Grapes are an excellent source of vitamins C and K. The following nutrition information is provided by the USDA.2\nCalories: 62\nFat: 0.3g\nSodium: 2mg\nCarbohydrates: 16g\nFiber: 1g\nSugars: 15g\nProtein: 0.6g\nVitamin C: 3.68mg\nVitamin K: 13.4mcg\nVitamin A: 4.6mcg \nHealth Benefits\nGrapes are a sweet, low-fat, and low-calorie treat. If you are trying to reduce your intake of processed foods or added sugars, grapes can be a good substitute for snacks like cookies and candy. Most of the health benefits of grapes come from the vitamins they contain. Help With Blood Clotting Vitamin K is important for strong bones and blood clotting.8 Note: If you take Coumadin (warfarin) or other blood thinners, your vitamin K intake should be consistent. Talk with a healthcare provider about your diet. Provide Antioxidants Grapes contain relatively large amounts of phytonutrients, especially flavonoids such as resveratrol (found in the skins of red grapes). Resveratrol has antioxidants that may help to lower the risk for high cholesterol, high blood pressure, blood clots, and heart disease.";
String Green_apple_t = "Green appleBenefits";
String Green_apple_d =
    "Health Benefits\n\n“An apple a day keeps the doctor away,” the saying goes. Considering the many health benefits that come with eating apples, this dietary proverb may not be too far from the truth. Here are a few of the health benefits you can get from eating green apples: Improve Heart Health Eating apples has been shown to improve heart health, lowering the risk of developing\ncardiovascular diseases.\nThe exact reason apples improve heart health is unclear. One contributing factor may be the high levels of dietary fiber in apples, as dietary fiber has been linked to lowering LDLcholesterol.\nReduce Risk of Developing Type 2 Diabetes Eating as few as a couple of green apples each week may reduce your chances of developing type 2 diabetes, according to one study, though more research needs to be done. It remains unclear whether the compounds in green apples help people manage their diabetes symptoms.\nNutrition\nGreen apples aren’t just packed with dietary fiber. They are also a good source of:\nVitamin A\nVitamin C\nCalcium\nIron";
// String Green_grapes
String Mango_t = "Mango Benefits";
String Mango_d =
    "Mango Nutrition\n\nThe following nutrition information for one cup of raw mango pieces (165g) is provided by the USDA.1\nCalories: 99\nFat: 0.6g\nSodium: 2mg\nCarbohydrates: 25g\nFiber: 2.6g\nSugars: 23g\nProtein: 1.4g\nVitamin C: 60mg\nVitamin E: 1.5mg\nFolate: 71mcg\nHealth Benefits\nThe vitamins and antioxidants in mango provide several health benefits. Improves Cell Function Vitamin C helps improve cell health in the body. Vitamin C is essential for immune system function, strong connective tissue, and healthy blood vessel walls. Vitamin C deficiency is rare in the United States, but getting an insufficient amount of the vitamin can lead to poor wound healing, joint pain, and, in extreme cases, scurvy, which can be fatal if untreated. Aids Fluid Balance The potassium in mango (and lack of sodium) may help regulate blood pressure and body fluid balance, particularly plasma volume.4 Adults are advised to consume at least 2,600 milligrams of potassium (for women) to 3,400 milligrams of potassium (for men) each day.A single serving of mango provides 277milligrams.";
String Orange_t = "orang Benefits";
String Orange_d =
    "Nutrition\n\nHere’s the nutritional breakdown for 1\norange (140 grams) (3Trusted Source):\nCalories: 66\nWater: 86% by weight\nProtein: 1.3 grams\nCarbs: 14.8 grams\nSugar: 12 grams\nFiber: 2.8 grams\nFat: 0.2 grams\nVitamin C: 92% of the Daily Value (DV)\nFolate: 9% of the DV\nCalcium: 5% of the DV\nPotassium: 5% of the DV\nHealth benefits of oranges\nAccording to research findings, regularly\nconsuming citrus fruits, like oranges, may\nbenefit your health in a number of ways.\nHelps promote heart health\nHeart disease is currently the world’s most\ncommon cause of premature death.\nA number of nutrients and plant compounds\nfound in oranges, including vitamin C,\nflavonoids, and carotenoids, may help\npromote heart health and reduce the risk of\nheart disease if you consume them";
String Pear_t = "pears Benefits";
String Pear_d =
    "Pear Nutrition Facts\n\n One medium-sized pear (178g) provides 101 calories, 0.6g of protein, 27g of carbohydrates, and 0.3g of fat. Pears are an excellent source of fiber, vitamin K, and potassium. The following nutrition information is provided by the USDA.2 \nCalories: 101\nFat: 0.3g\nSodium: 1.8mg\nCarbohydrates: 27g\nFiber: 5.5g\nSugars: 17g\nProtein: 0.6g\nVitamin K: 7.8mcg\nPear Benefits for Health Like many fruits and vegetables, pears offer health benefits because of their fiber and antioxidants. These compounds mean pears can help support the immune system, reduce inflammation, and reduce the risk of stroke and chronic diseases including diabetes, high blood pressure, and heart disease. Helps Repair Cells One medium-sized pear contains about 8 milligrams of vitamin C. This vitamin is important for cell growth and repair as well as preventing oxidative damage. Vitamin C has been shown to support immune function, aid in the healing of cuts and bruises, and even protect against infectious diseases.8 In addition, pear skin contains flavonoids, phenolics, and triterpenes that have antioxidant and anti-inflammatory properties.";
// String Plum
String Pomegranate_t = "ppomegranate Benefits";
String Pomegranate_d =
    "Pomegranate Nutrition Facts\n\nOne pomegranate (282g) provides 234\ncalories, 4.7g of protein, 52.7g of\ncarbohydrates, and 3.3g of fat. Pomegranate\nseeds, or arils, are a very good source of fiber\nand rich in potassium, phosphorus,\nmagnesium, and calcium. This nutrition\ninformation, for one pomegranate that is 4\ninches in diameter, is provided by the USDA.1\nCalories: 234\nFat: 3.3g\nSodium: 8.4mg\nCarbohydrates: 29g\nFiber: 11.3g\nSugars: 38.6g\nProtein: 4.7g\nPotassium: 666mg\nMagnesium: 33.8mg\nIron: 0.8mg\nVitamin C: 28.8mg\nFolate: 107.2mcg\nVitamin K: 46.2mcg\nHealth Benefits\nPomegranate seeds and juice contain\ncompounds and nutrients with healthpromoting qualities.\nHelps Build Bones, Cartilage, and Muscle\nPomegranates provide lots of vitamin C (Lascorbic acid). This vitamin is essential for good bone structure, cartilage, muscle, and blood vessels. It also aids in the absorption of iron and promotes wound healing. Vitamin C must be consumed through the diet because our bodies are unable to make it. Fights Oxidative Stress According to the National Institutes of Health, Ongoing research is examining whether vitamin C, by limiting the damaging effects of free radicals through its antioxidant activity, might help prevent or delay the development of";
// String Raspberries
String Red_apple_t = "Red Apples Benefits";
String Red_apple_d =
    "Nutrition Facts of Red Apples with Ski\n\n(1 large 3-1/4″ dia 223g)\nCalories 116 DV* = 6%\nCarbohydrate 30.8 g DV* = 10%\nDietary Fiber 5.4 g DV* = 21%\nVitamin C 10.3 mg DV* = 17%\nVitamin K 4.9 mcg DV* = 6%\nVitamin B6 0.1mg DV* = 5%\nVitamin A 120 IU DV* = 2%\nVitamin E (Alpha Tocopherol) 0.4 mg DV*= 2%\nPotassium 239 mg DV* = 7%\nFolate 6.7 mcg DV* = 2%\nCalcium 13.4 mg DV* = 1%\nProtein 0.6 g DV* = 1%\nMagnesium 11.2 mg DV* = 3%\nManganese 0.1 mg DV* = 4%\nbenefits\nFor Digestive Health\nApples are abundant in fiber and they have\na special type of soluble fiber called pectin\nwhich has shown to improve digestion.\nPectin has been found to curb diarrheacausing\nbacteria and it adds bulk to stools\nwhich can alleviate diarrhea.\nFurther, apple skin comes with a good\nsource of insoluble fiber called cellulose\nwhich helps food pass through the\ndigestive tract efficiently. This can ease";
String Strawberry_t = "Strawberry Benefits";
String Strawberry_d =
    "Strawberry Nutrition Facts\n\n One cup of halved strawberries (152g) includes 49 calories, 1g of protein, 12g of carbohydrates, and 0.5g of fat. Strawberries also are an excellent source of vitamin C, fiber, and potassium. The following nutrition information is provided by the USDA.1 \nCalories: 49\nFat: 0.5g\nSodium: 1.5mg\nCarbohydrates: 11.7g\nFiber: 3g\nSugars: 7.4g\nProtein: 1g\nVitamin C: 89.4mg\nPotassium: 233mg\nMagnesium: 19,8mg\nHealth Benefits\nStrawberries owe their vibrant hue to the array\nof antioxidants they possess. Here are some of\nthe ways that strawberries support good health. Prevents High Blood Sugar Berries are one of the lowest-sugar fruits, with several benefits for diabetes management. Not only are strawberries high in fiber, which helps keep blood sugars stable, but they may also be able to decrease the rise in blood sugar that typically occurs following a meal. Strawberries protect elevated blood sugar levels by reducing the uptake and transport of glucose in the intestines.3 Eases Arthritis Symptoms Strawberries have been shown to reduce inflammation for people living with osteoarthritis of the knee. Osteoarthritis is an inflammatory condition that causes significant pain during flare-ups. Studies show that consuming a 50-gram beverage of";
String Watermelon_t = "watermelon Benefits";
String Watermelon_d =
    "Nutrition Facts\n\nWatermelon consists mostly of water (91%)\nand carbs (7.5%). It provides almost no\nprotein or fat and is very low in calories.\nThe nutrients in 2/3 cup (100 grams) of raw\nwatermelon are (1Trusted Source):\nCalories: 30\nWater: 91%\nProtein: 0.6 grams\nCarbs: 7.6 grams\nSugar: 6.2 grams\nFiber: 0.4 grams\nFat: 0.2 grams\nHealth Benefits of Watermelons\nWatermelons and their juice are linked to\nseveral health benefits.\nLower Blood Pressure\nHigh blood pressure is a major risk factor for\nchronic disease and premature death\n(25Trusted Source).\nWatermelon is a good source of citrulline,\nwhich is converted into arginine in your\nbody. Both of these amino acids aid nitric\noxide production.\nNitric oxide is a gas molecule that causes the\ntiny muscles around your blood vessels to\nrelax and dilate. This leads to a reduction in\nblood pressure (26Trusted Source).\nSupplementing with watermelon or its juice\nmay reduce blood pressure and arterial\nstiffness in people with high blood pressure\n(27Trusted Source, 28Trusted Source,\n29Trusted Source, 30Trusted Source).\nReduced Insulin Resistance";

// String Yellow_apple
String Pineapple_t = "pineapple Benefits";
String Pineapple_d =
    "Pineapple Nutrition Facts\n\n One cup of pineapple chunks (165g) provides 82 calories, 0.9g of protein, 22g of carbohydrates, and 0.2g of fat. Pineapple is an excellent source of vitamin C. The following nutrition information is provided by the USDA.1 \nCalories: 82.5\n\nFat: 0.2g\nSodium: 1.7mg\nCarbohydrates: 22g\nFiber: 2.3g\nSugars: 16.3g\nProtein: 0.9g\nVitamin C: 79mg\nVerywell Fit\nSearch\nSearch\nVerywell Health\nVerywell Mind\nVerywell Family Ad NUTRITION FACTS FRUIT AND VEGETABLES Pineapple Nutrition Facts and Health Benefits By Barbie Cervoni MS, RD, CDCES, CDN Updated on September 15, 2022 Medically reviewed by Marisa Moore, RDN,\nMBA\nPineapple, annotated\nVerywell / Alexandra Shytsman\nTable of Contents\nVIEW ALL\nTable of Contents\nNutrition Facts\nHealth Benefits\nAllergies\nAdverse Effects\nVarieties\nPineapple is a nutritious and delicious fruit with several unique health benefits. If you follow a";
